routes:
# static content container
  - context: /example/*
    url: http://core-staticcontent
  - context: /jbossorg/*
    url: http://core-staticcontent
  - context: /netflix/*
    url: http://core-staticcontent

# 3party services
  - context: /hello-app1/*
    url: http://hello-app1:8080
  - context: /hello-app2/*
    url: http://hello-app2:8080
